### ISSUE TITLE
particles are way bigger than on the gif

### ISSUE THREAD

**Issue by andreyorst** [elizagamedev/power-mode.el#1]
each particle is like the double size of the character:

![image](https://user-images.githubusercontent.com/19470159/120699545-2ee9cc00-c4b9-11eb-8dcb-7d20d4b13c9f.png)

I'm on GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4) of 2021-05-30 running in a Wayland session on Fedora 34 with GNOME 40

**Comment by elizagamedev** [comment]
Hm, weird. The particles are supposed to be small 2x1 embedded frames with character height 4 times less than the parent frame. It could be that it doesn't set the font faces correctly if it is loaded before the theme, or if the theme sets faces differently than I expect. What theme are you using?

**Comment by andreyorst** [comment]
hm, I think I should've also mentioned that I'm using 2k display, with font scaling set to 1.33 size of the original font.

This is DOOM theme `doom-spacegrey`, although disabling theme doesn't fix the issue:

![image](https://user-images.githubusercontent.com/19470159/120706556-ed115380-c4c1-11eb-9630-a2e2f995ace4.png)

**Comment by elizagamedev** [comment]
Hmm, I see. I'll see if I can repro it on a hidpi display.

**Comment by andreyorst** [comment]
I've tried on my other machine that doesn't have hidpi display, and particles are still big. Maybe some modes like global-tab-line-mode is active in these frames? I remember some childframe based packages for completion had to explicitly disable modes that add header-line or tab-line and hide modeline.

**Comment by elizagamedev** [comment]
I think I was able to fix this with my most recent commit. Can you please verify?

**Comment by andreyorst** [comment]
> I think I was able to fix this with my most recent commit. Can you please verify?

No, particles are still big, but the misalignment from #2 seems to be more manageable now, but still there in maximized window

**Comment by 354651432** [comment]
I have the problem too, may I have an option to set its size,
and my emacs works should be after some minutes, I don't know if it is a problem, thanks

**Comment by 354651432** [comment]
and my doom-modeline disappeared

**Comment by Dickby** [comment]
I don't know if this is the reason, but i get much bigger particles 
if i set `(setq frame-inhibit-implied-resize t)`
