### ISSUE TITLE
Prevents minibuffer from popping up, and echo area

### ISSUE THREAD

**Issue by andreyorst** [elizagamedev/power-mode.el#2]
Here's how opened minibuffer looks like:

![image](https://user-images.githubusercontent.com/19470159/120706774-2ba70e00-c4c2-11eb-8562-00b36b1c7f7c.png)

It's like another window is layered on top of it.

Here's how it looks without power-mode:

![image](https://user-images.githubusercontent.com/19470159/120706883-4ed1bd80-c4c2-11eb-8acf-f5fdef41c09b.png)

Also happens with isearch:

![image](https://user-images.githubusercontent.com/19470159/120707027-7aed3e80-c4c2-11eb-997c-9b9b0a1ade52.png)

**Comment by elizagamedev** [comment]
The shake effects work by embedding a frame in the root frame, which explains the layered effect, but it doesn't explain the weird focus and sizing issues here. Do you have your dotfiles hosted somewhere so I could attempt to repro?

**Comment by andreyorst** [comment]
emacs config: https://gitlab.com/andreyorst/dotfiles/-/tree/master/.config/emacs

I've tested this on a machine without hidpi display and it had no issue, but when I've increased fon scaling the misalignment appeard instantly, without the need to restart Emacs. Maybe that's a hint to this mistery?
