### ISSUE TITLE
Exception in power-mode--make-shake-frame

### ISSUE THREAD

**Issue by io12** [elizagamedev/power-mode.el#3]
Really cool package! I had the issue though where it would have errors inside `power-mode--make-shake-frame`, because in
```lisp
(setcdr (assq (car pair) frame-parameters) (cdr pair))
```
the part `(assq (car pair) frame-parameters)` would return `nil`.

**Comment by elizagamedev** [comment]
I think this may be fixed with the latest commit, can you verify?

**Comment by io12** [comment]
Yes, thanks!
