### ISSUE TITLE
Can't type without clicking mouse if switching between applications

### ISSUE THREAD

**Issue by derekperrin** [elizagamedev/power-mode.el#4]
If I try to multitask, when I switch my focus back to emacs I can't immediately type. I need to use the mouse to click within the editor somewhere in order to type again. This happens if I try using alt-tab and if I just switch applications with the mouse.

**Comment by elizagamedev** [comment]
Yeah, I've noticed this behavior too. I think I have an idea of how to fix it.

**Comment by elizagamedev** [comment]
Should be fixed now!
